[firebase]
type = "service_account"
project_id = "spin-b5c3f"
private_key_id = "0fd86fba31a182659b827ca694ffe4fcb24eb098"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDCTDwhK8+LVEf1
PLV7oTrjE0PL9WIoC4VmmRkUOk8MbC/gzOWcA1A+o2TVW7nAhlnSVo8+ZcpnGZFn
ul4GUak5q8FiUJv4aHP8hD43f6oIKNZ3vb0Mw9xT9RWf2OLuhEz5UsZkXpbH1G0Z
EGUMHG1wlJxzEUo0Yj1LT2mNV5qk08sFgK5JswUcdb5SKA9dOZYrbRR4XxM6PBwW
YhyYXDF7ODUoPz4ObyoKCiJeD7kBtS0pKiRI6vTiMkiSh6nyz5DJJ9AcD5AGpMuQ
ZD6fl6WBlcyJfOaKkFt9n8T6EFY5Gy2zGl3YY+8ROzMkCS7Uo1TTK41hzYFEPjRV
aNTa+iTiipFy0
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@spin-b5c3f.iam.gserviceaccount.com"
client_id = "109902648898976945792"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc@spin-b5c3f.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
